---
# backup
- name: Backup current sshd_config
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.bak
    remote_src: yes

# authenticatie en authorisatie
- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: restart sshd

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart sshd

- name: Disable empty passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
  notify: restart sshd

- name: Allow only specific users
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?AllowUsers'
    line: 'AllowUsers admin'
  notify: restart sshd

# - name: Ensure authorized key is present
#   ansible.builtin.authorized_key:
#     user: "{{ ansible_control_user }}"
#     key: "{{ lookup('file', 'ssh_public_key_file') }}"

- name: Limit authentication attempts
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxAuthTries'
    line: 'MaxAuthTries 3'
  notify: restart sshd

# Network access
- name: Disable X11 forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding'
    line: 'X11Forwarding no'
  notify: restart sshd

# session management
- name: Set login grace time
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?LoginGraceTime'
    line: 'LoginGraceTime 30'
  notify: restart sshd

- name: Set SSH idle timeout
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ClientAliveInterval'
    line: 'ClientAliveInterval 300'
  notify: restart sshd

- name: Set SSH max retries before disconnect
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ClientAliveCountMax'
    line: 'ClientAliveCountMax 2'
  notify: restart sshd

# validatie
- name: Validate sshd config
  ansible.builtin.command:
    cmd: sshd -t -f /etc/ssh/sshd_config
  changed_when: false
