---
- name: Install chrony
  ansible.builtin.package:
    name: chrony
    state: present

- name: Enable and start chrony
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: yes
