---
- name: Load IPVS kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ ipvs_kernel_modules }}"
  loop_control:
    label: "{{ item }}"

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/ipvs.conf
    content: "{{ ipvs_kernel_modules | join ('\n') }}\n"
    mode: '0644'
