---
all:
  children:
    k8s:
      hosts:
        k8s-test-1:
          ansible_host: 10.0.2.22
          ansible_user: admin
        k8s-test-2:
          ansible_host: 10.0.2.20
          ansible_user: admin
        k8s-test-3:
          ansible_host: 10.0.2.21
          ansible_user: admin
        k8s-test-4:
          ansible_host: 10.0.2.24
          ansible_user: admin
