#SPDX-License-Identifier: MIT-0
---
# defaults file for kubernetes
kubernetes_version: "1.29.2"
kubernetes_release: "0"

kubernetes_node_packages:
  - "kubelet-{{ kubernetes_version }}-{{ kubernetes_release }}"
  - "kubeadm-{{ kubernetes_version }}-{{ kubernetes_release }}"

kubernetes_controlplane_packages:
  - "kubectl-{{ kubernetes_version }}-{{ kubernetes_release }}"

cni_plugin: flannel
kube_pod_cidr: ""

kube_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"

single_node: true
