---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_facts['swaptotal_mb'] | int > 0
  changed_when: true

- name: Disable swap permanently in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*\s+swap\s+.*)$'
    replace: '# \1'
