---
- name: Ensure sysctl params for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
  loop:
    - { name: "net.bridge.bridge-nf-call-iptables", value: 1 }
    - { name: "net.ipv4.ip_forward", value: 1 }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: 1 }
