---
- name: Set swap
  import_tasks: 01_swap.yml

- name: Set kernel modules
  import_tasks: 02_kernel.yml

- name: Set sysctl
  import_tasks: 03_sysctl.yml

- name: SELinux
  import_tasks: 04_selinux.yml

- name: Time Synchronization
  import_tasks: 05_timesync.yml

- name: Firewall settings
  import_tasks: 06_firewalld.yml
