# roles/kubernetes_bootstrap/tasks/main.yml
---
- name: Create helm-admin serviceaccount
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: helm-admin
        namespace: kube-system

- name: Bind helm-admin to cluster-admin
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: helm-admin-cluster-admin
      subjects:
        - kind: ServiceAccount
          name: helm-admin
          namespace: kube-system
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io

