#SPDX-License-Identifier: MIT-0
---
# tasks file for k8sinstall
- name: Add Kubernetes repository
  import_tasks: reporhel.yml
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Kubernetes
  import_tasks: install.yml
