#SPDX-License-Identifier: MIT-0
---
# defaults file for k8sinstall
kubernetes_version: "1.29"
kubernetes_release: ".2"

kubernetes_node_packages:
  - "kubelet-{{ kubernetes_version }}{{ kubernetes_release }}"
  - "kubeadm-{{ kubernetes_version }}{{ kubernetes_release }}"

kubernetes_controlplane_packages:
  - "kubectl-{{ kubernetes_version }}{{ kubernetes_release }}"
