all:
  children:
    controlplane:
      hosts:
        node3:
          ansible_host: 10.0.2.22 # alma 9.7
          ansible_user: admin
    workers:
      hosts:
        node2:
          ansible_host: 10.0.2.21 # alma 10.1
          ansible_user: admin
        node4:
          ansible_host: 10.0.2.24 # alma 10 kitten
          ansible_user: admin