all:
  children:
    controlplane:
      hosts:
        almacontrolnode:
          ansible_host: 192.168.8.191
          ansible_user: admin
          ansible_ssh_port: "{{ new_ssh_port }}"
    workers:
      hosts:
        almaworkernode1:
          ansible_host: 192.168.8.166
          ansible_user: admin
          ansible_ssh_port: "{{ new_ssh_port }}"
        almaworkernode2:
          ansible_host: 192.168.8.221
          ansible_user: admin
          ansible_ssh_port: "{{ new_ssh_port }}"