#SPDX-License-Identifier: MIT-0
---
# defaults file for common
python_packages:
  - python3
  - python3-pip

python_pip_packages:
  - kubernetes>=26.1.0
  - PyYAML
  - jsonpatch

python_imports:
  - kubernetes
  - yaml
  - jsonpatch

k8s_kernel_modules:
  - overlay
  - br_netfilter

sysctl_params:
  - { name: net.bridge.bridge-nf-call-iptables,  value: 1 }
  - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
  - { name: net.ipv4.ip_forward,                 value: 1 }

common_firewalld_enabled: true
common_firewalld_trusted_interfaces:
  - cni0
  - flannel.1

common_firewalld_open_ports:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250/tcp
  - 10251/tcp
  - 10252/tcp
