---
- name: Ensure containerd service is running
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Install Kubernetes packages (all nodes)
  ansible.builtin.package:
    name: # "{{ kubernetes_node_packages }}"
      - "kubelet-{{ kubernetes_version }}{{ kubernetes_release }}"
      - "kubeadm-{{ kubernetes_version }}{{ kubernetes_release }}"
    state: present

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: Ensure kubelet is stopped before kubeadm init
  ansible.builtin.systemd:
    name: kubelet
    state: stopped
