#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app_juiceshop
- name: Create Juice Shop namespace
  ansible.builtin.command: >
    kubectl apply -f -
  environment:
    KUBECONFIG: /home/admin/.kube/config
  args:
    stdin: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: juiceshop

- name: Add Git repository credentials to ArgoCD
  ansible.builtin.command: >
    kubectl apply -f -
  environment:
    KUBECONFIG: /home/admin/.kube/config
  args:
    stdin: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: juiceshop-git-repo
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        url: https://github.com/skatingm-cmd/juice-shop-git.git
        username: git
        password: "{{ git_token }}"

- name: Create ArgoCD Application for Juice Shop
  ansible.builtin.command: >
    kubectl apply -f -
  environment:
    KUBECONFIG: /home/admin/.kube/config
  args:
    stdin: |
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: juiceshop
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://github.com/skatingm-cmd/juice-shop-git.git
          targetRevision: main
          path: .
          helm:
            releaseName: juiceshop
        destination:
          server: https://kubernetes.default.svc
          namespace: juiceshop
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
