---
- name: Start kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started

- name: Wait for Kubernetes API to become available
  ansible.builtin.command: kubectl get nodes
  register: kubectl_check
  retries: 10
  delay: 15
  until: kubectl_check.rc == 0
  changed_when: false

