#SPDX-License-Identifier: MIT-0
---
# tasks file for k8scontrolconfig
- name: Assert node is member of controlplane group
  ansible.builtin.assert:
    that:
      - inventory_hostname in groups['controlplane']
    fail_msg: >
      This role may only be run on control-plane nodes.

- name: Load CNI defaults
  import_tasks: loadcnidefault.yml

- name: Kubeadm init
  import_tasks: init.yml

- name: Kube configuration for root
  import_tasks: kubeconfig.yml

- name: Install CNI plugin
  import_tasks: "cni/{{ cni_plugin }}.yml"

- name: RBAC configuration
  import_tasks: rbac.yml

- name: Start kubelet
  import_tasks: kubeletstart.yml

- name: Label control plane node
  import_tasks: labelnode.yml

- name: Generate and publish join commands
  import_tasks: joincommand.yml
