---
- name: Ensure SystemdCgroup is enabled
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  notify: Restart containerd

- name: Ensure correct pause image is set
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'sandbox_image = .*'
    replace: 'sandbox_image = "registry.k8s.io/pause:3.9"'
  notify: Restart containerd
