---
- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Check if containerd config exists
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: containerd_config_stat

- name: Generate default containerd config
  ansible.builtin.command: containerd config default
  register: containerd_default_config
  changed_when: false
  when: not containerd_config_stat.stat.exists

- name: Write containerd default config
  ansible.builtin.copy:
    content: "{{ containerd_default_config.stdout }}"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  when: not containerd_config_stat.stat.exists
  notify: Restart containerd

