---
- name: Configure crictl to use containerd
  ansible.builtin.copy:
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: '0644'
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 10
      debug: false

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started
