#SPDX-License-Identifier: MIT-0
---
# tasks file for containerd
- name: Docker Repo
  import_tasks: reporhel.yml

- name: Install Containerd
  import_tasks: install.yml

- name: Basic configurations for Containerd
  import_tasks: config.yml

- name: Configure SystemCgroup
  import_tasks: cgroup.yml

- name: Configure crictl
  import_tasks: crictl.yml
