# SPDX-License-Identifier: MIT-0
---
- name: Helm installation preparation
  import_tasks: prep.yml

- name: Install Helm
  import_tasks: install.yml

- name: Verify the Helm installation
  import_tasks: verification.yml
