---
- name: Afsluiten van virtuele machines die aan staan
  hosts: all
  gather_facts: no
  tasks:
    - name: Controleer of de VM aanstaat
      command: "virsh list --state-running --name"
      register: vm_status
      changed_when: false
      failed_when: false

    - name: Sluit de VM af als deze aan staat
      command: "virsh shutdown {{ item }}"
      loop: "{{ vm_status.stdout_lines }}"
      when: vm_status.stdout_lines | length > 0
      ignore_errors: yes

    - name: Geef een melding als er geen VM's aan staan
      debug:
        msg: "Er zijn geen virtuele machines die aan staan."
      when: vm_status.stdout_lines | length == 0
