#SPDX-License-Identifier: MIT-0
---
# tasks file for k8spreflight
- name: Kubernetes preflight checks
  ansible.builtin.debug:
    msg: "Running Kubernetes preflight checks"

- name: Check swap
  import_tasks: swap.yml

- name: Check sysctl
  import_tasks: sysctl.yml

- name: Check containerd
  import_tasks: containerd.yml

- name: Check hostname
  import_tasks: hostname.yml

- name: Check kubernetes control node
  import_tasks: kubernetescontrol.yml
  when: inventory_hostname in groups['controlplane']

- name: Check Kubernetes worker nodes
  import_tasks: kubernetesworker.yml
  when: inventory_hostname in groups['workers']
