---
- name: Check ip_forward sysctl
  ansible.builtin.command: sysctl -n net.ipv4.ip_forward
  register: ip_forward
  changed_when: false

- name: Fail if ip_forward is not enabled
  ansible.builtin.fail:
    msg: "net.ipv4.ip_forward must be set to 1"
  when: ip_forward.stdout != "1"

- name: Check bridge-nf-call-iptables sysctl
  ansible.builtin.command: sysctl -n net.bridge.bridge-nf-call-iptables
  register: br_nf_iptables
  changed_when: false

- name: Fail if bridge-nf-call-iptables is not enabled
  ansible.builtin.fail:
    msg: >
      net.bridge.bridge-nf-call-iptables must be set to 1.
      Did you run the common role?
  when: br_nf_iptables.stdout != "1"
