---
- name: Ensure kube config dir exists
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: "0700"

- name: Install admin kubeconfig for root
  ansible.builtin.copy:
    src: "{{ kubeconfig_path }}"
    dest: /root/.kube/config
    remote_src: true
    mode: "0600"