---
- name: Ensure firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Add CNI interfaces to trusted zone
  ansible.posix.firewalld:
    zone: trusted
    interface: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ common_firewalld_trusted_interfaces }}"
  when: common_firewalld_enabled

- name: Open required Kubernetes ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ common_firewalld_open_ports }}"
  when: common_firewalld_enabled