- name: Installeer k8s en ArgoCD op AlmaLinux
  hosts: almaNode1
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - sudoPassword.yml
    - gitKey.yml
  vars:
    ansible_become_password: "{{ sudo_password }}"
    git_token: "{{ git_token }}"
  gather_facts: yes
  tasks:
    - name: Create argocd namespace
      ansible.builtin.shell: |
        kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: /home/admin/.kube/config
