---
- name: Debug
  debug:
    var: hostvars

- name: Join node to Kubernetes cluster
  ansible.builtin.command:
    cmd: "{{ hostvars.[groups['controlplane'][0]].kubeadm_join_worker }}"
  args:
    creates: /etc/kubernetes/kubelet.conf

