---
- name: Label node as worker
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    kind: Node
    name: "{{ inventory_hostname }}"
    api_version: v1
    definition:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
  delegate_to: "{{ groups['controlplane'][0] }}"

