#SPDX-License-Identifier: MIT-0
---
# tasks file for k8sworkerconfig
- name: Assert node is member of workers group
  ansible.builtin.assert:
    that:
      - inventory_hostname in groups['workers']
    fail_msg: >
      This role may only be run on workers nodes.

- name: Join worker node to cluster
  import_tasks: join.yml

- name: Start kubelet
  import_tasks: kubelet.yml

- name: Label worker node
  import_tasks: label.yml
