all:
  children:
    controlplane:
      hosts:
        node2:
          ansible_host: 10.0.2.21
          ansible_user: admin
    workers:
      hosts:
        node6:
          ansible_host: 10.0.2.25
          ansible_user: admin
        node7:
          ansible_host: 10.0.2.26
          ansible_user: admin
