---
kernel_modules:
  - overlay
  - br_netfilter

k8s_control_plane_ports:
  - 6443/tcp    # API server
  - 2379-2380/tcp  # etcd
  - 10250/tcp
  - 10259/tcp
  - 10257/tcp

k8s_worker_ports:
  - 10250/tcp
  - 30000-32767/tcp   # NodePort range (ingress)

# Pod network (CNI-dependent)
k8s_pod_network_cidr: 10.244.0.0/16     # Flannel default
# k8s_pod_network_cidr: 192.168.0.0/16  # Calico default

k8s_ingress_ports:
  - 80/tcp
  - 443/tcp
