---
- name: Check if node already exists in cluster
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    name: "{{ ansible_facts['hostname'] }}"
    kubeconfig: /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['controlplane'][0] }}"
  register: node_info
  failed_when: false

- name: Join worker to cluster
  command: "{{ hostvars[groups['controlplane'][0]].kubeadm_join_cmd.stdout }} --cri-socket unix:///var/run/containerd/containerd.sock"
  when: node_info.resources | length == 0

- name: Wait for node to become Ready
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    name: "{{ ansible_facts['hostname'] }}"
    kubeconfig: /etc/kubernetes/admin.conf
  register: node_status
  until: >
    node_status.resources is defined and
    node_status.resources | length > 0 and
    (
      node_status.resources[0].status.conditions
      | selectattr('type', 'equalto', 'Ready')
      | selectattr('status', 'equalto', 'True')
      | list | length > 0
    )
  retries: 20
  delay: 15
  delegate_to: "{{ groups['controlplane'][0] }}"
