---
- name: Initialize Kubernetes control plane
  command: >
    kubeadm init
    --apiserver-advertise-address={{ kube_apiserver_advertise_address }}
    --pod-network-cidr={{ kube_pod_cidr }}
    --upload-certs
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

