---
- name: Ensure kube config dir exists
  file:
    path: /root/.kube
    state: directory
    mode: "0700"

- name: Install admin kubeconfig for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: true
    mode: "0600"

