---
- name: Disable swap if enabled
  ansible.builtin.command: swapoff -a
  when: ansible_facts['swaptotal_mb'] | int > 0
  changed_when: ansible_facts['swaptotal_mb'] | int > 0

- name: Comment out swap entries in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*\s+swap\s+.*)$'
    replace: '# \1'