---
- name: Persist kernel modules for Kubernetes
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ common_kernel_modules }}"
    
